#!/usr/bin/env python3
"""Regenerate programs/readme.md from program metadata and optional preview.png files."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def generate(root=ROOT):
    root = Path(root)
    manifest = root / "build" / "manifest.json"
    sizes = {p["name"]: p["size"] for p in json.loads(manifest.read_text())["programs"]} if manifest.exists() else {}
    lines = ["# Sector 256 programs", "", "Generated by `python scripts/programs_md.py`.", ""]
    for folder in sorted((root / "programs").iterdir(), key=lambda p: p.name.upper()):
        if not folder.is_dir():
            continue
        data = json.loads((folder / "program.json").read_text())
        name = folder.name.upper()
        lines += [f"## {name}", "", data["description"], "",
                  f"Category: {data['category']}. " + (f"Stored payload: **{sizes[name]} bytes**." if name in sizes else "Build to calculate size."), "",
                  f"[Assembly source](programs/{folder.name}/main.asm)", ""]
        if (folder / "preview.png").exists():
            lines += [f"![{name} preview](programs/{folder.name}/preview.png)", ""]
    (root / "programs/readme.md").write_text("\n".join(lines))
    readme = root / "readme.md"
    if readme.exists() and "(programs/readme.md)" not in readme.read_text():
        readme.write_text(readme.read_text() + "\n[Browse the programs](programs/readme.md).\n")


if __name__ == "__main__":
    generate()
